### ISSUE TITLE
YMIS mail doesn't show all my snaps

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft-monthly-stats-email#9]
I received a *Your Month in Snaps* mail over the weekend.
I have a large number of published snaps. Only 10 are listed. It's not that the others have fewer installs, because most of them have hundreds or more.

Listed are mame, mindustry, mgba, gphotos-sync, toot, ffscreencast, emu2, openboardview, matterbridge, pwbm. Lots more that aren't. 

Note: I have a snap in the store called "null" which may be causing this :D

**Comment by jkfran** [comment]
Cleaning all the [null duplicates on Marketo](https://github.com/canonical-web-and-design/snapcraft-monthly-stats-email/pull/12) didn't solve this issue. After debugging it a bit, looks like a Marketo issue because the list is working fine when visiting the "View it in your browser" link but snaps are missing in the actual email.

I create a ticket on Marketo support. case: 01964897
